### ISSUE TITLE
Environment entities that are obsolete (archived/soft deleted) are not removed from the mobile app

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12355]
### Bug Description

Environment entities that are obsolete (archived/soft deleted) are not removed from the mobile app by the logic that removes with the synchronization the other obsolete entities.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/c5018d8d-45d0-42e0-88a0-119a668948b4)

### Reproduction Steps

1. Configure the 149 line from SynchronizaDataAsync to look like the screenshot above;
2. Save the changes and start the mobile app;
3. Log in with a user that has access to the Environment Directory;
4. Trigger a synchronization;
5. Observe that all environment entities are displayed in the mobile app, regardless of whether they are active, archived, or deleted.

### Expected Behavior

The environment entities that are archived or soft deleted should be removed from the mobile app.

### Affected Area(s)

Android app

### SORMAS Version

1.87.0

### Android version/Browser

Chrome, Android Studio

### User Role(s)

Admin+NatUser, Default Environmental Surveillance User

### Server URL

local machine

**Comment by MateStrysewske** [comment]
@adinaflorea9 Could you test this again, please? It's possible that I fixed this in #12361

**Comment by adinaflorea9** [comment]
@MateStrysewske I will and if it is fixed I will close this ticket.

**Comment by adinaflorea9** [comment]
@MateStrysewske  the issue is still reproducible. I have this currently set:
 
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/37c276de-c11e-4743-a937-9fe806728d07)

I have no active environments entities, only archived and soft deleted ones, but in the mobile app, all the environments that are within the user's jurisdiction are still displayed. I triggered multiple synchronizations, and re-synchronize data and also I treid with 2 different  Environmental surveillance Officer users.

**Comment by adinaflorea9** [comment]
Currently the behavior has shifted a bit meaning that for active entities that were within the user's jurisdiction that were already synchronized in the mobile app, once they are deleted from the web app and then another regular synchronization is triggered - the entities also no longer appear in the mobile app. 

But if the user then triggers a re-synchronize data type of synchronization from the mobile app, the entities that were previously active and then made soft deleted are displayed again.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.89.0-SNAPSHOT(dab979d).
